# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNo', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expiryDate', models.DateField()),
                ('cardHolderName', models.CharField(max_length=30)),
            ],
        ),
    ]
